spring:
  datasource:
    url: jdbc:h2:file:./data/gym-prod;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: "prod-secret"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: false

server:
  port: 8081

logging:
  level:
    com.epam.training: INFO