spring.datasource.url=jdbc:h2:mem:gymdb-local;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
logging.level.root=DEBUG
logging.level.com.epam.training=DEBUG
spring.jpa.show-sql=true
