spring.datasource.url=jdbc:h2:file:./data/gymdb-prod;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=changeit_in_prod
logging.level.root=ERROR
logging.level.com.epam.training=WARN
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
