spring.datasource.url=jdbc:h2:mem:gymdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.h2.console.enabled=true
server.port=8080
logging.level.root=INFO
logging.level.com.epam.training=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{transactionId}] %logger{36} - %msg%n
spring.profiles.active=local
management.endpoints.web.exposure.include=health,info,metrics
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
app.brute-force.max-attempts=3
app.brute-force.block-duration-minutes=5
spring.jackson.serialization.write-dates-as-timestamps=false
