# ============================================================
# DEV profile - shared development server
# ============================================================
spring.datasource.url=jdbc:h2:mem:gymdb_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=dev
spring.datasource.password=devpass

spring.h2.console.enabled=false

logging.level.root=INFO
logging.level.com.epam.training=INFO

app.hibernate.ddl-auto=create-drop
app.hibernate.show-sql=false